### ISSUE TITLE
Base Map

### ISSUE THREAD

**Issue by filipzava** [CzechInvest/webmap#13]
Jakou pouzime podkladovou mapu? (OMT, MapBox)
Jachym: 
V tuhle chvíli bych šel do OMT - je to pokud vím levnější a je to v podstatě českej projekt (i když tedy ve Švýcarsku). Rozjet celou Klokaní infrastrukturu jednou v budoucnu na našem serveru už umím, taže je tam i nějaká rozumná možnost rozvoje.

**Comment by filipzava** [comment]
@jachym Asi bych spis doporucoval rastrovy podklad. Jde o to, ze je vektor sice peknej (snadneji jim ho muzeme prizpusobit), ale jelikoz chceme podkladovku jako doplnek pro orientaci, nemuzeme si dovolit spotrebovat vykon pro rendrovani podkladu, myslim, ze nam bude stacit vykon tak akorat na data. Na druhou stranu je pravda, ze ta mapka bude defaultne mala. Spis bych doporucoval pouzit rastr. sluzby MapBoxu, alespon pro zacatek. Souhlasis ?

**Comment by jachym** [comment]
nemam vubec nic proti. i kdyz ty klokani mapy jsou imho celkem optimalizovany - a klokan umi wmts taky, potom budem licitovat o cene, radsi bych podporil nekoho v evrope nez v usa. ted bych prosil tam dat neco, co pujde hned a jednoduse

**Comment by filipzava** [comment]
ok

**Comment by jachym** [comment]
Na podkladové mapě je někdy název města česky někdy anglicky viz Carlsbad a Plzeň... co s tím? Chtělo by to nějak sjednotit.. .)
Taky na podkladovce nejsou nijak výrazné hlavní silniční tahy (dálnice především). Pokud podkladová vrstva neumožňuje editaci, tak bych je dala do modulu doprava jako samostatnou vrstvu.

**Comment by jachym** [comment]
viz #35

**Comment by jachym** [comment]
vyreseno
