### ISSUE TITLE
formát čísel

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#18]
U krajů je oškolivé formátování čísel. Každá položka v měnu by u sebe měla mít funkci, která text nebo hlavně číslo naformátuje. Příklad:

3.14159265359 -> 3.14
0.22345 -> 22%
100000000 -> 100 000 000

**Comment by marcel-dancak** [comment]
Kedze samotne funkcie v konfiguracii vrstiev asi nebude mozne pouzit (ak to bude JSON a neskor ulozeny v redux store), vidim to bud na nami preddefinovane formaty, alebo mozno trochu univerzalnejsie pouzitim vstavanych formatovacich funkcii, alebo kniznic.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat
Numeral.js
react-number-format
