### ISSUE TITLE
silnice prvni a druhe tridy jsou stejne

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#23]
1. vyhodit silnice 2 třídy - žere to výkon a informaci to moc nepřínáší
2. opravit prováznost s tlačítkem a souborem primary.geojson

**Comment by marcel-dancak** [comment]
Opravil som prepojenie na správny dataset. Stále platí, že silnice 2 třídy je lepšie vyhodiť úplne?

**Comment by jachym** [comment]
zatím nechat, dík
