### ISSUE TITLE
Vrstva letiště - moc atributů

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#26]
Zobrazit pouze atributy

- name
- iata
- icao

**Comment by jachym** [comment]
nebo to mám vytáhnout z těch dat já?

**Comment by jachym** [comment]
data jsem upravil tak, aby obsahovala jenom použitelné atributy

platí i pro přístavy

@marcel-dancak můžeš to prosím aktualizovat?

**Comment by marcel-dancak** [comment]
@jachym nechal si tam aj 'website', tak aj ten som nechal zobrazovať, v prípade že je zadaný. Niektoré linky už ale nie sú aktuálne, tak neviem či sa zaktualizujú, alebo ten atribút nezobrazíme vôbec.

**Comment by jachym** [comment]
pockej, to by melo byt url, jak to udelam

**Comment by jachym** [comment]
fixed

**Comment by marcel-dancak** [comment]
Teraz som si všimol, že niektoré linky začínajú http:// protokolom, iné nie. A preto potom niektoré nefungujú. Zdá sa mi, že rovnaký problém bol už riešený pri iných vrstvách.

**Comment by jachym** [comment]
jééje, děkuju za testování - opraveno.
