### ISSUE TITLE
Načítání vektorových vrstev

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#3]

**Comment by filipzava** [comment]
**Jak zajistit data ?** 
Mame 2 moznosti (neberu v potaz dotaz na API).

* importovana hardcodem. Tedy neco jako `import rk = './data/rk.json'`. Ale data mame v jinem repu.
* `fetch` metoda na raw git pro dev mode (mohu nastavit reverzni proxy webpacku, ze bude smerovat prave na raw git), z produkce to bude brat z deployovaneho baliku. 

Vybral bych druhou moznost. Co vy ? Nejake jine napady ?

**Comment by marcel-dancak** [comment]
Cez import by som nesiel, to skor pripojit ten repozitar do adresara 'public' (ci uz cez git submodule ako navrhol Jachym, alebo si to naklonovat), bolo by to sice offline riesenie, ale na vyvoj by to nemuselo byt zle.

Zalezi aj, ako bude pristupovat k datam produkcna verzia. Ako si to myslel s tym deployovanym balikom?

**Comment by jachym** [comment]
No, nic proti zrani z gitu (jde to vůbec? - jiná doména) ale myslel jsem, že bychom to udělali přes `git submodule` ?

**Comment by jachym** [comment]
Chodí, zavírám.
