### ISSUE TITLE
Soc. ekon údaje na úroveň ORP

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#32]
* Stejný údaje jako pro Kraje
* Ruční přepínání v seznamu modulů (ne automaticky na zoom)
* Už zapnutý panel s kraji/orp se smaže
* Slepá mapa ORP + zvlášť JSON s daty
* Slepá mapa Krajů + zvlášť JSON s daty

**Comment by jachym** [comment]
Data mám v mailu od Ivany ze dne 23.01.2018

**Comment by marcel-dancak** [comment]
Prvá komplikácia na ktorú som narazil sú farby. Pri krajoch mal každý kraj svojú farbu, pri ORP by tých farieb bolo už veľa. Chcelo by to novú stratégiu priradzovania farieb, či úž náhodnú alebo napr. fixne podľa poradia pri označovaní. A asi by bolo fajn spraviť to jednotne pri kraje aj ORP.
