### ISSUE TITLE
změna fontu a posun CI hesla

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#37]
V levo-dole "Spojujeme a podporujeme" je jiný font než všude jinde. Posunout dolu, aby to nestrašilo v mapě

**Comment by marcel-dancak** [comment]
Tých možností ako vložiť svg obrázok je viacero, img element ma zdá sa najväčšie limity...
Ak by chceli aby sa ten text aj prekladal podľa zvoleného jazyka, môže sa to prerobiť na komponent.
