### ISSUE TITLE
Úprava ikonek

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#46]
V kategorii "VVI & Vzdělávání" má vrstva "Vědecko-technické parky" jinou ikonku než ostattní - je tam navíc raketka. Raketku pryč, nechat jenom propojené atomy.

![image](https://user-images.githubusercontent.com/1460823/35854372-7b2a3b40-0b30-11e8-98d2-beb0f92ebf0e.png)

**Comment by marcel-dancak** [comment]
Táto vrstva spolu s vrstvami 'Podnikatelsky inkubator' a 'Akcelerator' (v kat. STARTUPOVY EKOSYSTEM) ešte nie sú doštýlované. Odkladal som to na prediskutovanie v Prahe...

Tieto vrstvy sú z rovnakých dát, a pritom sú v rôznych kategóriach. Niektoré objekty sú Vědeckotechnické parky, no zároveň aj Podnikateľské inkubátory alebo Akcelerátory. Preto som skúšal menšie experimenty s miešanými ikonami.
