### ISSUE TITLE
Úprava ikonek

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#47]
Ve vrstvě "Startupový ekosystém" mají vrstvy "Podnikatelský inkubátor" a "Akcelerátor" kolečko. Chceme raketku, jako všechny ostatní.

![image](https://user-images.githubusercontent.com/1460823/35854454-b0f71cc0-0b30-11e8-89bf-41dad0433ee6.png)

**Comment by marcel-dancak** [comment]
Rovnaký dôvod ako u #46
