### ISSUE TITLE
uplně zrušit panely při zúžení výřezu nad určitou úroveň

### ISSUE THREAD

**Issue by jachym** [CzechInvest/webmap#58]
Ahoj,

pro lepší integraci do dalších stránek potřebujeme úplně zmenšit/odstranit panely (horní a dolní), od určité výšky okna

Např: výška 400 px, zmizí dolní lišta. Výška 300 px: zmizí i horní lišta

šlo by?

**Comment by marcel-dancak** [comment]
Určite skrývať aj horný panel? Bez možnosti zapínania vrstiev mi potom príde mapa dosť nepoužiteľná.

**Comment by jachym** [comment]
Ahoj, ano. Bude to sloužit jenom jako malý panel na stránkách, kde bude umístěno tlačítko "zvětšit mapu" a ona se pak roztáhne na fullscreen nebo prostě do většího divu

**Comment by marcel-dancak** [comment]
V tom prípade by to šlo, ale bude to o niečo komplikovanejšie, ak to má byť závislé na rozmeroch elementu mapového kontainera. Doteraz som na responzivitu používal iba CSS, to ale vie reagovať iba na veľkosť okna, nie konkrétneho elementu. A to asi nebude fungovať dobre, ak šírka kontainera bude menšia, ako je celá stránka, čo myslím že nastane...
Asi to nakoniec budeme musieť zabaliť do iframe elementu, ale tak aby sa nerozbili iné veci, ktoré potrebujú prístup na hlavnú stránku.

**Comment by jachym** [comment]
jasny, no ja navrhuju to vyzkouset a videt co to bude delat :-/
